name: Release CI
on: [push]
jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn

      - name: lint
        run: yarn lint && yarn tsc

      - name: release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
